apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: <postgresql user in base64>
  postgres-password: <postgresql password in base64>

---

apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
type: Opaque
data:
  token: <telegram token in base64>

---

apiVersion: v1
kind: Secret
metadata:
  name: app-tls
type: kubernetes.io/tls
data:
  tls.crt: <ssl certificate in base64>
  tls.key: <key for ssl certificate in base64>
  
 
  