apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-redis
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/redis-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-redis-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pg
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pg-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-pg-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi